FROM node:22-alpine AS build

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

WORKDIR /app

COPY . .

RUN yarn install

RUN cd packages/web && yarn install
RUN cd packages/web && yarn build

FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx/variables.conf.template /etc/nginx/templates/00-variables.conf.template

COPY --from=build /app/packages/web/dist /var/www/html
