FROM node:22-alpine as build

WORKDIR /app

COPY . .

RUN yarn install

RUN cd packages/server && yarn install
RUN cd packages/server && yarn build

FROM node:22-alpine

WORKDIR /app

COPY packages/server/package.json ./

COPY --from=build /app/packages/server/dist ./dist
COPY --from=build /app/packages/server/node_modules ./node_modules

ENV PORT=4321
EXPOSE ${PORT}

CMD ["node", "dist/index.js"]
