FROM node:22-alpine as build

WORKDIR /app

COPY . .

RUN yarn install

RUN cd packages/web && yarn install
RUN cd packages/web && yarn build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/packages/web/dist /usr/share/nginx/html
