/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as PrivacyImport } from './routes/privacy';
import { Route as NewImport } from './routes/new';
import { Route as AboutImport } from './routes/about';
import { Route as IdImport } from './routes/$id';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any);

const NewRoute = NewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

const IdRoute = IdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/$id': {
      id: '/$id';
      path: '/$id';
      fullPath: '/$id';
      preLoaderRoute: typeof IdImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    '/new': {
      id: '/new';
      path: '/new';
      fullPath: '/new';
      preLoaderRoute: typeof NewImport;
      parentRoute: typeof rootRoute;
    };
    '/privacy': {
      id: '/privacy';
      path: '/privacy';
      fullPath: '/privacy';
      preLoaderRoute: typeof PrivacyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$id': typeof IdRoute;
  '/about': typeof AboutRoute;
  '/new': typeof NewRoute;
  '/privacy': typeof PrivacyRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$id': typeof IdRoute;
  '/about': typeof AboutRoute;
  '/new': typeof NewRoute;
  '/privacy': typeof PrivacyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/$id': typeof IdRoute;
  '/about': typeof AboutRoute;
  '/new': typeof NewRoute;
  '/privacy': typeof PrivacyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/$id' | '/about' | '/new' | '/privacy';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/$id' | '/about' | '/new' | '/privacy';
  id: '__root__' | '/' | '/$id' | '/about' | '/new' | '/privacy';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  IdRoute: typeof IdRoute;
  AboutRoute: typeof AboutRoute;
  NewRoute: typeof NewRoute;
  PrivacyRoute: typeof PrivacyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  AboutRoute: AboutRoute,
  NewRoute: NewRoute,
  PrivacyRoute: PrivacyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$id",
        "/about",
        "/new",
        "/privacy"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$id": {
      "filePath": "$id.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/new": {
      "filePath": "new.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
